#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(dirname $(readlink -f ${BASH_SOURCE[0]}))"

listeners_pid_file="/tmp/eww-listeners.pid"

generated_dir="/tmp/eww-generated"
mkdir -p "$generated_dir"

for f in "$SCRIPT_DIR/generators"/*; do
	generated_name="$generated_dir/$(basename "$f").yuck"
	"$f" > "$generated_name"
	echo "(include '$generated_name')" > "$generated_dir/all.yuck"
done

# Kill previous instance
eww -c "$SCRIPT_DIR" kill || true
kill $(cat "$listeners_pid_file") || true

for f in "$SCRIPT_DIR/windows"/*.yuck; do
	basef="$(basename $f)"
	window_name="${basef%.yuck}"
	if [ "$window_name" == "all" ]; then continue; fi
	eww open -c "$SCRIPT_DIR" "$window_name"
done

# Start listeners
for f in "$SCRIPT_DIR/listeners"/*; do
	"$f" &
done
jobs -p > "$listeners_pid_file"

