#!/usr/bin/env bash

set -euo pipefail

if [ "$(ls -1 ~/.config/sway/start.d/ | wc -l)" = "0" ]; then
  echo "no start hook to run in \"~/.config/sway/start.d/\"" >&2
  return
fi

for f in ~/.config/sway/start.d/*; do
  echo "executing $f hook..."
  $f
  echo "$f successfully executed."
done

