#!/usr/bin/env bash

SCRIPT_DIR="$(dirname $(readlink -f ${BASH_SOURCE[0]}))"
EWW_CONFIG_DIR="$SCRIPT_DIR/.."

# Initial values
eww -c "$EWW_CONFIG_DIR" update backlight="$(blightctl percentage)"
eww -c "$EWW_CONFIG_DIR" update volume-mute="$(blightctl is-mute && echo "true")"

# Close overlay by default
eww -c "$EWW_CONFIG_DIR" close backlight-overlay

while read -r line; do 
	kill $(jobs -p) &> /dev/null
	eww -c "$EWW_CONFIG_DIR" open backlight-overlay &

	eww -c "$EWW_CONFIG_DIR" update backlight="$line"

	(sleep 1s; eww -c "$EWW_CONFIG_DIR" close backlight-overlay) &
done < <(blightctl stream)
