#!/usr/bin/env bash

SCRIPT_DIR="$(dirname $(readlink -f ${BASH_SOURCE[0]}))"
EWW_CONFIG_DIR="$SCRIPT_DIR/.."

# Initial values
eww -c "$EWW_CONFIG_DIR" update volume="$(volumectl percentage)"
eww -c "$EWW_CONFIG_DIR" update volume-mute="$(volumectl is-mute && echo "true")"

# Close overlay by default
eww -c "$EWW_CONFIG_DIR" close volume-overlay

while read -r line; do 
	kill $(jobs -p) &> /dev/null
	eww -c "$EWW_CONFIG_DIR" open volume-overlay &

	if [ "$line" = "mute" ]; then
		eww -c "$EWW_CONFIG_DIR" update volume-mute=true
	elif [ "$line" = "unmute" ]; then
		eww -c "$EWW_CONFIG_DIR" update volume-mute=false
	else
		eww -c "$EWW_CONFIG_DIR" update volume="$line"
	fi

	(sleep 1s; eww -c "$EWW_CONFIG_DIR" close volume-overlay) &
done < <(volumectl stream)
